### ISSUE TITLE
Login button not shown in android app

### ISSUE THREAD

**Issue by deepupathak** [meteor/accounts#10]
Hi,
I am trying to develop mobile app of todo in 1.3. When I do so, login button is not showing in android app. However its working perfectly on the browser as well as in emulator.
Any clue/solution for this issue ?

Thanks

**Comment by NicholasEli** [comment]
Did you clarify a server during the Meteor run process?

**Comment by abernix** [comment]
For questions, you should try the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).

That said, the long delay in responding here is because this repository itself is not the active "Accounts" package, which is still a part of the main Meteor repo.  This branch was an attempt to extract the accounts packages, but is still a work in progress.  Further issues with the active `accounts-*` packages should go on the [main Meteor repo](https://github.com/meteor/meteor/). :smile:
