### ISSUE TITLE
Is it possible to remove the registration function?

### ISSUE THREAD

**Issue by BehrouzRiahu** [meteor/accounts#16]
It might seem weird but I want to remove the registration function and only leave the login feature, is it possible to be done through `accounts-ui` package?

**Comment by addynaik** [comment]
one approach would be to configure the router to map the signup route to a page that says registration is closed or some other page.

**Comment by abernix** [comment]
For questions, you should try the [Meteor forums](http://forums.meteor.com/) or [Stack Overflow tagged with `meteor`](https://stackoverflow.com/questions/tagged/meteor).

That said, the long delay in responding here is because this repository itself is not the active "Accounts" package, which is still a part of the main Meteor repo.  This branch was an attempt to extract the accounts packages, but is still a work in progress.  Further issues with the active `accounts-*` packages should go on the [main Meteor repo](https://github.com/meteor/meteor/). :smile:
