### ISSUE TITLE
iOS Cordova sign-in failing due to updated Google security restrictions: "403 - disallowed_useragent"

### ISSUE THREAD

**Issue by ddett** [meteor/accounts#18]
When trying to sign in to our Meteor Cordova app with the accounts-google package as we did successfully for the last 12 months we now see the following error message:

> 403 - disallowed_useragent
> 
> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browser are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization request in the browser.

Is there even a way for the accounts package to deal with Google's "new security restrictions", or will we have to look at specific Cordova plugins like this: https://github.com/gbenvenuti/cordova-plugin-google-sign-in-ios ?

**Comment by rolandNanoTubes** [comment]
+1

**Comment by techieyann** [comment]
It's interesting that it isn't an issue in Android, just iOS. Is Google preferring chrome, or is Safari acting weird?

**Comment by MrAnkan** [comment]
+1

**Comment by jimmythigpen** [comment]
+1

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

Since there are a handful of upvotes on this issue, I've migrated it over to meteor/meteor#8531. Closing here - thanks!

**Comment by Umesh2Patel** [comment]
+1

**Comment by Umesh2Patel** [comment]
I am getting similar error while signing into Waze carpool app from my iphone
