### ISSUE TITLE
accounts-facebook param is not a valid string

### ISSUE THREAD

**Issue by jasongrishkoff** [meteor/accounts#21]
Hi there, this seems to be an issue with version 1.1.0 of accounts-facebook.

```
Error: Failed to fetch identity from Facebook. failed [400] {"error":{"message":"\"fields\" param is not a valid string","type":"OAuthException","code":2500,"fbtrace_id":"D9N1WOUOvS\/"}}
    at getIdentity (packages/facebook-oauth.js:125:20)
    at Object.handleAuthFromAccessToken (packages/facebook-oauth.js:35:18)
    at Object.handleOauthRequest (packages/facebook-oauth.js:56:19)
    at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
    at middleware (packages/oauth.js:203:5)
    at packages/oauth.js:176:5
```

**Comment by abernix** [comment]
I believe your problem was fixed with https://github.com/meteor/meteor/commit/2c5dda1675a9e3526e3a926d3ec2b45d0fab14c6, which is a fix on the main repo.

That said, this repository itself actually is not the active "Accounts" package, which is still a part of the main Meteor repo.  This branch was an attempt to extract the accounts packages, but is still a work in progress.  Further issues with the active `accounts-*` packages should go on the [main Meteor repo](https://github.com/meteor/meteor/). :smile:
