### ISSUE TITLE
Accounts Facebook iOS simulator "You are not logged in. You are not logged in. Please log in and try again"

### ISSUE THREAD

**Issue by NicholasEli** [meteor/accounts#9]
After moving from Meteor 1.2x to 1.3.x Facebook login has stopped working and I get the following error message "You are not logged in. You are not logged in. Please log in and try again." 

I've tried stack overflow and the forums only to find others with the same issue for iOS and the simulator alike. 

I'm not using any special oAuth requirements just the package as is and rendered to the template with the login button handlebars call.

Works fine on desktop.

**Comment by Yonben** [comment]
+1 here, but on 1.4

**Comment by NicholasEli** [comment]
I am getting ready to start a new project and absolutely need this feature to work. I am wondering if it has been resolved in anyway?

I had to remove it from my last project and ship it without the Facebook login as it did not pertain to MVP.

**Comment by mikkelking** [comment]
bump

**Comment by NicholasEli** [comment]
I posted a stack overflow question with a bounty here http://stackoverflow.com/questions/39936777/meteor-1-3-accounts-facebook-login-for-ios-not-working . It has gained some traction in up votes.

**Comment by mcoenca** [comment]
Same issue on Meteor 1.3 new production builds only, mainly Android. 
I have only changed like 10 lines in my codebase completely unrelated to facebook and cordova, previous builds work like a charm.

Debug builds work fine, so super easy to debug and test new things with 30min < 2 days waits for my changes to be published to the play store, even in beta test, and no debugging utility for production builds because production apps can't be debugged with Chrome. 

The main pain point about this is **the fucking shitty debugging message given.**

I've looked all over the internet, It could mean so many different things at so many layers: platform not added to facebook, android hashes badly configured, Urls not authorized, cordova facebook SDK not working with websockets, incorrect app Ids, pages refreshes because of hot code push... I'm going crazy spending days on this old freelance project dependent on mobile facebook login, just to make it work **again**. 

I wish we had a more detailed error message on the facebook login API dashboard...

Anyway. Ragequit.

**Comment by javascriptlove** [comment]
Updates on this? Anyone? @martijnwalraven

**Comment by santteegt** [comment]
@mcoenca did you find a solution ?

**Comment by NicholasEli** [comment]
I do not think this will get solved anytime soon. There is only one guy working at MDG currently on development.

**Comment by mcoenca** [comment]
I don't know how I solved it really. The issue disappeared in the midst of a lot of changes, that had no obvious relation with facebook.
I may have had a plugin config syntax error in my mobile-config.js, if i recall... but not sure.

**Comment by mcoenca** [comment]
Hmm. Ok I just had to update one of my mobile apps, and ran into this issue again. You're not going to believe me, but the issue was that I was building toward https://www.myapp.com **:443** like so

`meteor build ../builds --server=https://myapp.com:443`

... and when i did

`meteor build ../builds --server=https://myapp.com` 

it worked.

:call_me_hand: computers...

**Comment by jpmoyn** [comment]
Has this gotten solved yet? It seems a lot of people are having problems with getting facebook login to work with cordova. I am also having trouble.

**Comment by NicholasEli** [comment]
Still an issue

**Comment by hwillson** [comment]
Now that the [`accounts-*` packages can be used without requiring Blaze](https://github.com/meteor/meteor/blob/devel/History.md#v143-2017-02-13), there is no longer a reason to manage/maintain the `accounts-*` packages in a separate repo. The [`meteor/meteor/packages/accounts-*`](https://github.com/meteor/meteor/tree/devel/packages) packages are the official source of record, and this repo will be closed down in the not too distant future. All new accounts issues / feature requests should be logged within the main [`meteor/meteor`](https://github.com/meteor/meteor) repo. 

I've migrated this issue over to meteor/meteor#8533, so I'll close it here. The main meteor repo is much more closely monitored, so expect a follow up on this issue shortly. Thanks and sorry for the delay in responding!
